# Generated by Django 3.2.7 on 2021-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
