# Generated by Django 3.2.7 on 2021-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0004_auto_20211120_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
