# Generated by Django 3.2.7 on 2021-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0005_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='email',
            field=models.CharField(max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
