# Generated by Django 3.2.7 on 2021-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0006_auto_20211122_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantidade', models.IntegerField(max_length=100, verbose_name='Quantidade')),
            ],
        ),
    ]
