# Generated by Django 3.2.7 on 2021-11-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0007_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
