# Generated by Django 3.2.7 on 2021-11-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0010_auto_20211122_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='produto',
        ),
    ]
