# Generated by Django 3.2.7 on 2021-11-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0011_remove_instituicao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doacao.instituicao'),
            preserve_default=False,
        ),
    ]
