# Generated by Django 3.2.7 on 2021-11-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0012_produto_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doacao.instituicao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doacao.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doacao.usuario')),
            ],
        ),
    ]
