# Generated by Django 3.2.7 on 2021-11-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0013_auto_20211124_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.instituicao'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.produto'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.usuario'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.instituicao'),
        ),
    ]
